### ISSUE TITLE
How to implement BILSTM_ARE or BERT_ARE model in the jupyter notebook? 

### ISSUE THREAD

**Issue by ashokchhetri7** [ipavlopoulos/toxic_spans#31]
As far as I know, the sequential methods are all implemented in the notebook with the evaluation metrics. But the attention-based is not implemented. Have anyone implemented those models? 

I wanted to test the model, but I got a bit confused while implementing it on Google-Colab. Please let me know if anyone has implemented it. Any suggestions are warmly welcomed. Thanks!

**Comment by alexandrosXe** [comment]
a notebook training and evaluating BILSTM_ARE has now been added.

**Comment by ashokchhetri7** [comment]
Thank you so much! 
Can you please add the BERT_ARE too? I would be grateful.
