### ISSUE TITLE
Can we use trial data as validation data ?

### ISSUE THREAD

**Issue by talhaanwarch** [ipavlopoulos/toxic_spans#9]
Greetings. I want to know when will the validation data be released?

**Comment by ipavlopoulos** [comment]
Hi, I moved this question, along with a response, to [our Google Group](https://groups.google.com/d/msgid/toxic-spans/1c71cdc6-51f2-42e7-bc0f-dd2fd4f05605n%40googlegroups.com?utm_medium=email&utm_source=footer). Please follow up there.
